sonar.organization=javieramlc
sonar.projectKey=javieramlc_travel-adk-multiagent
sonar.projectName=travel-adk-multiagent
sonar.sources=.
sonar.exclusions=**/.venv/**, **/tests/**, **/__pycache__/**
sonar.python.version=3.11